import CountryFlag from "react-native-country-flag";

const countries = [
    // { label: "Afghanistan", value: "af-AFN", icon: () => <CountryFlag isoCode="af" size={15} /> },
    { label: "Albania", value: "al-ALL", icon: () => <CountryFlag isoCode="al" size={15} /> },
    { label: "Algeria", value: "dz-DZD", icon: () => <CountryFlag isoCode="dz" size={15} /> },
    // { label: "Andorra", value: "ad-EUR", icon: () => <CountryFlag isoCode="ad" size={15} /> },
    // { label: "Angola", value: "ao-AOA", icon: () => <CountryFlag isoCode="ao" size={15} /> },
    { label: "Antigua and Barbuda", value: "ag-XCD", icon: () => <CountryFlag isoCode="ag" size={15} /> },
    { label: "Argentina", value: "ar-ARS", icon: () => <CountryFlag isoCode="ar" size={15} /> },
    { label: "Armenia", value: "am-AMD", icon: () => <CountryFlag isoCode="am" size={15} /> },
    { label: "Australia", value: "au-AUD", icon: () => <CountryFlag isoCode="au" size={15} /> },
    { label: "Austria", value: "at-EUR", icon: () => <CountryFlag isoCode="at" size={15} /> },
    { label: "Azerbaijan", value: "az-AZN", icon: () => <CountryFlag isoCode="az" size={15} /> },
    // { label: "Bahamas", value: "bs-BSD", icon: () => <CountryFlag isoCode="bs" size={15} /> },
    // { label: "Bahrain", value: "bh-BHD", icon: () => <CountryFlag isoCode="bh" size={15} /> },
    // { label: "Bangladesh", value: "bd-BDT", icon: () => <CountryFlag isoCode="bd" size={15} /> },
    { label: "Barbados", value: "bb-BBD", icon: () => <CountryFlag isoCode="bb" size={15} /> },
    { label: "Belarus", value: "by-BYN", icon: () => <CountryFlag isoCode="by" size={15} /> },
    { label: "Belgium", value: "be-EUR", icon: () => <CountryFlag isoCode="be" size={15} /> },
    // { label: "Belize", value: "bz-BZD", icon: () => <CountryFlag isoCode="bz" size={15} /> },
    // { label: "Benin", value: "bj-XOF", icon: () => <CountryFlag isoCode="bj" size={15} /> },
    // { label: "Bhutan", value: "bt-BTN", icon: () => <CountryFlag isoCode="bt" size={15} /> },
    // { label: "Bolivia", value: "bo-BOB", icon: () => <CountryFlag isoCode="bo" size={15} /> },
    { label: "Bosnia and Herzegovina", value: "ba-BAM", icon: () => <CountryFlag isoCode="ba" size={15} /> },
    { label: "Botswana", value: "bw-BWP", icon: () => <CountryFlag isoCode="bw" size={15} /> },
    { label: "Brazil", value: "br-BRL", icon: () => <CountryFlag isoCode="br" size={15} /> },
    // { label: "Brunei", value: "bn-BND", icon: () => <CountryFlag isoCode="bn" size={15} /> },
    { label: "Bulgaria", value: "bg-BGN", icon: () => <CountryFlag isoCode="bg" size={15} /> },
    // { label: "Burkina Faso", value: "bf-XOF", icon: () => <CountryFlag isoCode="bf" size={15} /> },
    // { label: "Burundi", value: "bi-BIF", icon: () => <CountryFlag isoCode="bi" size={15} /> },
    // { label: "Cabo Verde", value: "cv-CVE", icon: () => <CountryFlag isoCode="cv" size={15} /> },
    { label: "Cambodia", value: "kh-KHR", icon: () => <CountryFlag isoCode="kh" size={15} /> },       
    { label: "Cameroon", value: "cm-XAF", icon: () => <CountryFlag isoCode="cm" size={15} /> },
    { label: "Canada", value: "ca-CAD", icon: () => <CountryFlag isoCode="ca" size={15} /> },
    { label: "Central African Republic", value: "cf-XAF", icon: () => <CountryFlag isoCode="cf" size={15} /> },
    { label: "Chad", value: "td-XAF", icon: () => <CountryFlag isoCode="td" size={15} /> },
    { label: "Chile", value: "cl-CLP", icon: () => <CountryFlag isoCode="cl" size={15} /> },
    { label: "China", value: "cn-CNY", icon: () => <CountryFlag isoCode="cn" size={15} /> },
    { label: "Colombia", value: "co-COP", icon: () => <CountryFlag isoCode="co" size={15} /> },
    // { label: "Comoros", value: "km-KMF", icon: () => <CountryFlag isoCode="km" size={15} /> },
    { label: "Congo (Congo-Brazzaville)", value: "cg-XAF", icon: () => <CountryFlag isoCode="cg" size={15} /> },
    { label: "Costa Rica", value: "cr-CRC", icon: () => <CountryFlag isoCode="cr" size={15} /> },
    { label: "Croatia", value: "hr-HRK", icon: () => <CountryFlag isoCode="hr" size={15} /> },
    // { label: "Cuba", value: "cu-CUP", icon: () => <CountryFlag isoCode="cu" size={15} /> },
    { label: "Cyprus", value: "cy-EUR", icon: () => <CountryFlag isoCode="cy" size={15} /> },
    { label: "Czech Republic", value: "cz-CZK", icon: () => <CountryFlag isoCode="cz" size={15} /> },
    // { label: "Democratic Republic of the Congo", value: "cd-CDF", icon: () => <CountryFlag isoCode="cd" size={15} /> },
    { label: "Denmark", value: "dk-DKK", icon: () => <CountryFlag isoCode="dk" size={15} /> },
    // { label: "Djibouti", value: "dj-DJF", icon: () => <CountryFlag isoCode="dj" size={15} /> },
    { label: "Dominica", value: "dm-XCD", icon: () => <CountryFlag isoCode="dm" size={15} /> },
    { label: "Dominican Republic", value: "do-DOP", icon: () => <CountryFlag isoCode="do" size={15} /> },
    { label: "Ecuador", value: "ec-USD", icon: () => <CountryFlag isoCode="ec" size={15} /> },
    { label: "Egypt", value: "eg-EGP", icon: () => <CountryFlag isoCode="eg" size={15} /> },
    { label: "El Salvador", value: "sv-USD", icon: () => <CountryFlag isoCode="sv" size={15} /> },
    // { label: "Equatorial Guinea", value: "gq-XAF", icon: () => <CountryFlag isoCode="gq" size={15} /> },
    // { label: "Eritrea", value: "er-ERN", icon: () => <CountryFlag isoCode="er" size={15} /> },
    { label: "Estonia", value: "ee-EUR", icon: () => <CountryFlag isoCode="ee" size={15} /> },
    // { label: "Eswatini (Swaziland)", value: "sz-SZL", icon: () => <CountryFlag isoCode="sz" size={15} /> },
    // { label: "Ethiopia", value: "et-ETB", icon: () => <CountryFlag isoCode="et" size={15} /> },
    // { label: "Fiji", value: "fj-FJD", icon: () => <CountryFlag isoCode="fj" size={15} /> },
    { label: "Finland", value: "fi-EUR", icon: () => <CountryFlag isoCode="fi" size={15} /> },
    { label: "France", value: "fr-EUR", icon: () => <CountryFlag isoCode="fr" size={15} /> },
    { label: "Gabon", value: "ga-XAF", icon: () => <CountryFlag isoCode="ga" size={15} /> },
    // { label: "Gambia", value: "gm-GMD", icon: () => <CountryFlag isoCode="gm" size={15} /> },
    { label: "Georgia", value: "ge-GEL", icon: () => <CountryFlag isoCode="ge" size={15} /> },
    { label: "Germany", value: "de-EUR", icon: () => <CountryFlag isoCode="de" size={15} /> },
    { label: "Ghana", value: "gh-GHS", icon: () => <CountryFlag isoCode="gh" size={15} /> },
    { label: "Greece", value: "gr-EUR", icon: () => <CountryFlag isoCode="gr" size={15} /> },
    { label: "Grenada", value: "gd-XCD", icon: () => <CountryFlag isoCode="gd" size={15} /> },
    // { label: "Guatemala", value: "gt-GTQ", icon: () => <CountryFlag isoCode="gt" size={15} /> },
    { label: "Guinea", value: "gn-GNF", icon: () => <CountryFlag isoCode="gn" size={15} /> },
    // { label: "Guinea-Bissau", value: "gw-XOF", icon: () => <CountryFlag isoCode="gw" size={15} /> },
    // { label: "Guyana", value: "gy-GYD", icon: () => <CountryFlag isoCode="gy" size={15} /> },
    // { label: "Haiti", value: "ht-HTG", icon: () => <CountryFlag isoCode="ht" size={15} /> },
    { label: "Honduras", value: "hn-HNL", icon: () => <CountryFlag isoCode="hn" size={15} /> },
    { label: "Hungary", value: "hu-HUF", icon: () => <CountryFlag isoCode="hu" size={15} /> },
    { label: "Iceland", value: "is-ISK", icon: () => <CountryFlag isoCode="is" size={15} /> },
    { label: "India", value: "in-INR", icon: () => <CountryFlag isoCode="in" size={15} /> },
    { label: "Indonesia", value: "id-IDR", icon: () => <CountryFlag isoCode="id" size={15} /> },
    // { label: "Iran", value: "ir-IRR", icon: () => <CountryFlag isoCode="ir" size={15} /> },
    // { label: "Iraq", value: "iq-IQD", icon: () => <CountryFlag isoCode="iq" size={15} /> },
    { label: "Ireland", value: "ie-EUR", icon: () => <CountryFlag isoCode="ie" size={15} /> },
    { label: "Israel", value: "il-ILS", icon: () => <CountryFlag isoCode="il" size={15} /> },
    { label: "Italy", value: "it-EUR", icon: () => <CountryFlag isoCode="it" size={15} /> },
    { label: "Jamaica", value: "jm-JMD", icon: () => <CountryFlag isoCode="jm" size={15} /> },
    { label: "Japan", value: "jp-JPY", icon: () => <CountryFlag isoCode="jp" size={15} /> },
    { label: "Jordan", value: "jo-JOD", icon: () => <CountryFlag isoCode="jo" size={15} /> },
    { label: "Kazakhstan", value: "kz-KZT", icon: () => <CountryFlag isoCode="kz" size={15} /> },
    { label: "Kenya", value: "ke-KES", icon: () => <CountryFlag isoCode="ke" size={15} /> },
    // { label: "Kiribati", value: "ki-AUD", icon: () => <CountryFlag isoCode="ki" size={15} /> },
    { label: "Kuwait", value: "kw-KWD", icon: () => <CountryFlag isoCode="kw" size={15} /> },
    { label: "Kyrgyzstan", value: "kg-KGS", icon: () => <CountryFlag isoCode="kg" size={15} /> },
    { label: "Laos", value: "la-LAK", icon: () => <CountryFlag isoCode="la" size={15} /> },
    { label: "Latvia", value: "lv-EUR", icon: () => <CountryFlag isoCode="lv" size={15} /> },
    { label: "Lebanon", value: "lb-LBP", icon: () => <CountryFlag isoCode="lb" size={15} /> },
    { label: "Lesotho", value: "ls-LSL", icon: () => <CountryFlag isoCode="ls" size={15} /> },
    // { label: "Liberia", value: "lr-LRD", icon: () => <CountryFlag isoCode="lr" size={15} /> },
    // { label: "Libya", value: "ly-LYD", icon: () => <CountryFlag isoCode="ly" size={15} /> },
    { label: "Liechtenstein", value: "li-CHF", icon: () => <CountryFlag isoCode="li" size={15} /> },
    { label: "Lithuania", value: "lt-EUR", icon: () => <CountryFlag isoCode="lt" size={15} /> },
    { label: "Luxembourg", value: "lu-EUR", icon: () => <CountryFlag isoCode="lu" size={15} /> },
    { label: "Madagascar", value: "mg-MGA", icon: () => <CountryFlag isoCode="mg" size={15} /> },
    // { label: "Malawi", value: "mw-MWK", icon: () => <CountryFlag isoCode="mw" size={15} /> },
    { label: "Malaysia", value: "my-MYR", icon: () => <CountryFlag isoCode="my" size={15} /> },
    // { label: "Maldives", value: "mv-MVR", icon: () => <CountryFlag isoCode="mv" size={15} /> },
    // { label: "Mali", value: "mlk-XOF", icon: () => <CountryFlag isoCode="ml" size={15} /> },
    { label: "Malta", value: "mt-EUR", icon: () => <CountryFlag isoCode="mt" size={15} /> },
    // { label: "Marshall Islands", value: "mh-USD", icon: () => <CountryFlag isoCode="mh" size={15} /> },
    // { label: "Mauritania", value: "mrMRU", icon: () => <CountryFlag isoCode="mr" size={15} /> },
    // { label: "Mauritius", value: "mu-MUR", icon: () => <CountryFlag isoCode="mu" size={15} /> },
    { label: "Mexico", value: "mx-MXN", icon: () => <CountryFlag isoCode="mx" size={15} /> },
    // { label: "Micronesia", value: "fm-USD", icon: () => <CountryFlag isoCode="fm" size={15} /> },
    { label: "Moldova", value: "md-MDL", icon: () => <CountryFlag isoCode="md" size={15} /> },
    { label: "Monaco", value: "mc-EUR", icon: () => <CountryFlag isoCode="mc" size={15} /> },
    // { label: "Mongolia", value: "mn-MNT", icon: () => <CountryFlag isoCode="mn" size={15} /> },
    // { label: "Montenegro", value: "me-EUR", icon: () => <CountryFlag isoCode="me" size={15} /> },
    { label: "Morocco", value: "ma-MAD", icon: () => <CountryFlag isoCode="ma" size={15} /> },
    // { label: "Mozambique", value: "mz-MZN", icon: () => <CountryFlag isoCode="mz" size={15} /> },
    { label: "Myanmar (Burma)", value: "mm-MMK", icon: () => <CountryFlag isoCode="mm" size={15} /> },
    // { label: "Namibia", value: "na-NAD", icon: () => <CountryFlag isoCode="na" size={15} /> },
    // { label: "Nauru", value: "nr-AUD", icon: () => <CountryFlag isoCode="nr" size={15} /> },
    { label: "Nepal", value: "np-NPR", icon: () => <CountryFlag isoCode="np" size={15} /> },
    { label: "Netherlands", value: "nl-EUR", icon: () => <CountryFlag isoCode="nl" size={15} /> },
    { label: "New Zealand", value: "nz-NZD", icon: () => <CountryFlag isoCode="nz" size={15} /> },
    { label: "Nicaragua", value: "ni-NIO", icon: () => <CountryFlag isoCode="ni" size={15} /> },
    { label: "Niger", value: "ne-XOF", icon: () => <CountryFlag isoCode="ne" size={15} /> },
    { label: "Nigeria", value: "ng-NGN", icon: () => <CountryFlag isoCode="ng" size={15} /> },
    // { label: "North Korea", value: "kp-KPW", icon: () => <CountryFlag isoCode="kp" size={15} /> },
    { label: "North Macedonia", value: "mk-MKD", icon: () => <CountryFlag isoCode="mk" size={15} /> },
    { label: "Norway", value: "no-NOK", icon: () => <CountryFlag isoCode="no" size={15} /> },
    { label: "Oman", value: "om-OMR", icon: () => <CountryFlag isoCode="om" size={15} /> },
    // { label: "Pakistan", value: "pk-PKR", icon: () => <CountryFlag isoCode="pk" size={15} /> },
    // { label: "Palau", value: "pw-USD", icon: () => <CountryFlag isoCode="pw" size={15} /> },
    { label: "Palestine", value: "ps-ILS", icon: () => <CountryFlag isoCode="ps" size={15} /> },
    { label: "Panama", value: "pa-PAB", icon: () => <CountryFlag isoCode="pa" size={15} /> },
    // { label: "Papua New Guinea", value: "pg-PGK", icon: () => <CountryFlag isoCode="pg" size={15} /> },
    { label: "Paraguay", value: "py-PYG", icon: () => <CountryFlag isoCode="py" size={15} /> },
    { label: "Peru", value: "pe-PEN", icon: () => <CountryFlag isoCode="pe" size={15} /> },
    { label: "Philippines", value: "ph-PHP", icon: () => <CountryFlag isoCode="ph" size={15} /> },
    { label: "Poland", value: "pl-PLN", icon: () => <CountryFlag isoCode="pl" size={15} /> },
    { label: "Portugal", value: "pt-EUR", icon: () => <CountryFlag isoCode="pt" size={15} /> },
    { label: "Qatar", value: "qa-QAR", icon: () => <CountryFlag isoCode="qa" size={15} /> },
    { label: "Romania", value: "ro-RON", icon: () => <CountryFlag isoCode="ro" size={15} /> },
    { label: "Russia", value: "ru-RUB", icon: () => <CountryFlag isoCode="ru" size={15} /> },
    { label: "Rwanda", value: "rw-RWF", icon: () => <CountryFlag isoCode="rw" size={15} /> },
    { label: "Saint Kitts and Nevis", value: "kn-XCD", icon: () => <CountryFlag isoCode="kn" size={15} /> },
    { label: "Saint Lucia", value: "lc-XCD", icon: () => <CountryFlag isoCode="lc" size={15} /> },
    { label: "Saint Vincent and the Grenadines", value: "vc-XCD", icon: () => <CountryFlag isoCode="vc" size={15} /> },
    // { label: "Samoa", value: "ws-WST", icon: () => <CountryFlag isoCode="ws" size={15} /> },
    // { label: "San Marino", value: "sm-EUR", icon: () => <CountryFlag isoCode="sm" size={15} /> },
    // { label: "Sao Tome and Principe", value: "st-STN", icon: () => <CountryFlag isoCode="st" size={15} /> },
    { label: "Saudi Arabia", value: "sa-SAR", icon: () => <CountryFlag isoCode="sa" size={15} /> },
    { label: "Senegal", value: "sn-XOF", icon: () => <CountryFlag isoCode="sn" size={15} /> },
    // { label: "Serbia", value: "rs-RSD", icon: () => <CountryFlag isoCode="rs" size={15} /> },
    { label: "Seychelles", value: "sc-SCR", icon: () => <CountryFlag isoCode="sc" size={15} /> },
    // { label: "Sierra Leone", value: "sl-SLL", icon: () => <CountryFlag isoCode="sl" size={15} /> },
    { label: "Singapore", value: "sg-SGD", icon: () => <CountryFlag isoCode="sg" size={15} /> },
    { label: "Slovakia", value: "sk-EUR", icon: () => <CountryFlag isoCode="sk" size={15} /> },
    { label: "Slovenia", value: "si-EUR", icon: () => <CountryFlag isoCode="si" size={15} /> },
    // { label: "Solomon Islands", value: "sb-SBD", icon: () => <CountryFlag isoCode="sb" size={15} /> },
    // { label: "Somalia", value: "so-SOS", icon: () => <CountryFlag isoCode="so" size={15} /> },
    { label: "South Africa", value: "za-ZAR", icon: () => <CountryFlag isoCode="za" size={15} /> },
    { label: "South Korea", value: "kr-KRW", icon: () => <CountryFlag isoCode="kr" size={15} /> },
    // { label: "South Sudan", value: "ss-SSP", icon: () => <CountryFlag isoCode="ss" size={15} /> },
    { label: "Spain", value: "es-EUR", icon: () => <CountryFlag isoCode="es" size={15} /> },
    { label: "Sri Lanka", value: "lk-LKR", icon: () => <CountryFlag isoCode="lk" size={15} /> },
    // { label: "Sudan", value: "sd-SDG", icon: () => <CountryFlag isoCode="sd" size={15} /> },
    // { label: "Suriname", value: "sr-SRD", icon: () => <CountryFlag isoCode="sr" size={15} /> },
    { label: "Sweden", value: "se-SEK", icon: () => <CountryFlag isoCode="se" size={15} /> },
    { label: "Switzerland", value: "ch-CHF", icon: () => <CountryFlag isoCode="ch" size={15} /> },
    // { label: "Syria", value: "sy-SYP", icon: () => <CountryFlag isoCode="sy" size={15} /> },
    { label: "Taiwan", value: "tw-TWD", icon: () => <CountryFlag isoCode="tw" size={15} /> },
    { label: "Tajikistan", value: "tj-TJS", icon: () => <CountryFlag isoCode="tj" size={15} /> },
    { label: "Tanzania", value: "tz-TZS", icon: () => <CountryFlag isoCode="tz" size={15} /> },
    { label: "Thailand", value: "th-THB", icon: () => <CountryFlag isoCode="th" size={15} /> },
    // { label: "Timor-Leste", value: "tl-USD", icon: () => <CountryFlag isoCode="tl" size={15} /> },
    // { label: "Togo", value: "tg-XOF", icon: () => <CountryFlag isoCode="tg" size={15} /> },
    // { label: "Tonga", value: "to-TOP", icon: () => <CountryFlag isoCode="to" size={15} /> },
    // { label: "Trinidad and Tobago", value: "tt-TTD", icon: () => <CountryFlag isoCode="tt" size={15} /> },
    { label: "Tunisia", value: "tn-TND", icon: () => <CountryFlag isoCode="tn" size={15} /> },
    { label: "Turkey", value: "tr-TRY", icon: () => <CountryFlag isoCode="tr" size={15} /> },
    // { label: "Turkmenistan", value: "tm-TMT", icon: () => <CountryFlag isoCode="tm" size={15} /> },
    // { label: "Tuvalu", value: "tv-AUD", icon: () => <CountryFlag isoCode="tv" size={15} /> },
    // { label: "Uganda", value: "ug-UGX", icon: () => <CountryFlag isoCode="ug" size={15} /> },
    { label: "Ukraine", value: "ua-UAH", icon: () => <CountryFlag isoCode="ua" size={15} /> },
    // { label: "United Arab Emirates", value: "gb-AED", icon: () => <CountryFlag isoCode="ae" size={15} /> },
    { label: "United Kingdom", value: "gb-GBP", icon: () => <CountryFlag isoCode="gb" size={15} /> },
    { label: "United States of America", value: "us-USD", icon: () => <CountryFlag isoCode="us" size={15} /> },
    { label: "Uruguay", value: "uy-UYU", icon: () => <CountryFlag isoCode="uy" size={15} /> },
    { label: "Uzbekistan", value: "uz-UZS", icon: () => <CountryFlag isoCode="uz" size={15} /> },
    // { label: "Vanuatu", value: "vu-VUV", icon: () => <CountryFlag isoCode="vu" size={15} /> },
    // { label: "Vatican City", value: "va-EUR", icon: () => <CountryFlag isoCode="va" size={15} /> },
    { label: "Venezuela", value: "ve-VES", icon: () => <CountryFlag isoCode="ve" size={15} /> },
    { label: "Vietnam", value: "vn-VND", icon: () => <CountryFlag isoCode="vn" size={15} /> },
    // { label: "Yemen", value: "ye-YER", icon: () => <CountryFlag isoCode="ye" size={15} /> },
    { label: "Zambia", value: "zm-ZMW", icon: () => <CountryFlag isoCode="zm" size={15} /> },
    // { label: "Zimbabwe", value: "zw-ZWL", icon: () => <CountryFlag isoCode="zw" size={15} /> },
];

export default countries;

    
