import { createTheme } from "@shopify/restyle";

const palette = {
  graySoft: "#A1A1A1",
  gray50: "#979797",
  gray40: "#929292",
  gray02: "#F6F6F6",
  gray03: "#F8F8F8",
  gray04: "#7F7F7F",
  gray05: "#B0B0B0",
  gray06: "#C0C0C0",
  gray07: "#909090",
  gray08: "#D0D0D0",
  gray09: "#C1C1C1",
  gray10: "#1E1E1E",
  gray11: "#C7C7C7",
  gray12: "#5E2A2A",
  gray13: "#A5A5A5",
  black: "#0B0B0B",
  black01: "#151515",
  black02: "#161616",
  black03: "#2A2A2A",
  black04: "#3A3A3A",
  black06: "#737373",
  white: "#FFFFFF",
  white01: "#FDFDFD",
  green01: "#AFFFEC",
  softWhite: "#F0F0F0",
  smootWhite: "#DEDEDE",
  smootWhite01: "#2E2E2E",
  smootWhite02: "#E4E4E4",
  success: "#EEF5E7",
  complement: "#0F4457",
  grayWhite: "#8B8B8B",
  smoot: "#E3F8FF",
  strongBlack: "#262626",
  smootBlack: "#343434",
  complementaryBlack: "#222222",
  blue: "#0A9DCA",
  blue02: "#10B4E7",
  red: "#CB0808",
  red01: "#FC3636",
  softSKin: "#01FFC2",
  darkBlack: "#000000",
  inputStatusSuccess: "#0AAD41",
  inputStatusSuccessBG: "#07280E",
  SettingsOptionItemValue: "#A6A6A6",
  warningText: "#825C22",
  warningIcon: "#F39200",
  warningbg: "#301E03",
  blueDark: "#093448",
  copyIcon: "#7D7D7D",
  actualBalanceText: "#6D6D6D",
  blueLight: "#CFF8FE",
  greenLight: "#00FFC2",
  borderBlueLight: "#CFF8FE",
  cyanSuperLight: "#F0FAFF",
  yellowLight: "#F8EAC8",
  iconDefault: "#CEEAF4",
};

const theme = createTheme({
  lightMode: {
    colors: {
      primary: palette.white01,
      blueDark: palette.blueDark,
      blueLight: palette.blueLight,
      gray: palette.gray10,
      borderBlueLight: palette.borderBlueLight,
      white: palette.white,
      actualBalance: palette.actualBalanceText,
      cyanSuperLight: palette.cyanSuperLight,
      yellowLight: palette.yellowLight,
      graySoft: palette.graySoft,
      darkBlack: palette.darkBlack,
      
      textContrast: palette.smoot,         
      contrast: palette.black,            
      secondaryText: palette.grayWhite,
    },
  },
  colors: {
    blue: palette.blue,
    blueDark: palette.blueDark,
    iconDefault: palette.iconDefault,
    greenLight: palette.greenLight,
    copyIcon: palette.copyIcon,
    mainBackground: palette.black,
    cardPrimaryBackground: palette.success,
    placeholderBackground: palette.gray40,
    placeholderLightBackground: palette.gray03,
    placeholderLight: palette.gray02,
    mainText: palette.complement,
    secondaryText: palette.grayWhite,
    textContrast: palette.smoot,
    contrast: palette.white,
    primarySummary: palette.strongBlack,
    contentSummary: palette.gray04,
    mainAction: palette.blue,
    mainActionState: palette.blue02,
    darkBlack: palette.smootBlack,
    darkBlack01: palette.black02,
    darkBlack03: palette.black03,
    darkBlack04: palette.darkBlack,
    darkBlack05: palette.black04,
    darkGray: palette.gray50,
    darkGray01: palette.red,
    deleteBackground: palette.red,
    contrastBackground: palette.softWhite,
    complementaryText: palette.complementaryBlack,
    smootText: palette.smootWhite,
    labelText: palette.gray05,
    borderInput: palette.black01,
    borderSelect: palette.smootWhite01,
    selectText: palette.gray06,
    selectLabel: palette.gray07,
    softSKin: palette.softSKin,
    listTitle: palette.smootWhite02,
    textLInk: palette.gray08,
    messageHeader: palette.gray09,
    roundedGray: palette.gray10,
    label: palette.gray11,
    deleteText: palette.red01,
    contrastText: palette.white01,
    inputStatusSuccess: palette.inputStatusSuccess,
    inputStatusSuccessBG: palette.inputStatusSuccessBG,
    switchTrackTrue: palette.smoot,
    switchThumbTrue: palette.softSKin,
    switchTrackFalse: palette.smoot,
    switchThumbFalse: palette.gray13,
    switchCardBG: palette.smoot,
    SettingsOptionItemValue: palette.SettingsOptionItemValue,
    warningText: palette.warningText,
    warningIcon: palette.warningIcon,
    warningbg: palette.warningbg,
  },
  spacing: {
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 40,
    "2xl": 80,
  },
  textVariants: {
    small: {
      fontFamily: "Inter_400Regular",
      fontSize: 10,
      lineHeight: 12,
    },
    titleCard: {
      fontFamily: "Inter_700Bold",
      fontSize: 30,
      lineHeight: 36,
    },
    descriptionCard: {
      fontFamily: "Inter_400Regular",
      fontSize: 12,
      lineHeight: 14,
    },
    captionCard: {
      fontFamily: "Inter_400Regular",
      fontSize: 14,
      lineHeight: 16,
    },
    textInfo: {
      fontFamily: "Inter_500Medium",
      fontSize: 16,
      lineHeight: 19,
    },
    helper: {
      fontFamily: "Inter_300Light",
      fontSize: 10,
      lineHeight: 12,
    },
    modalSummary: {
      fontFamily: "Inter_700Bold",
      fontSize: 16,
      lineHeight: 19,
    },
    contentSummary: {
      fontFamily: "Inter_400Regular",
      fontSize: 16,
      lineHeight: 19,
    },
    button: {
      fontFamily: "Inter_600SemiBold",
      fontSize: 16,
      lineHeight: 19,
    },
    inputCode: {
      fontFamily: "Inter_700Bold",
      fontSize: 24,
      lineHeight: 29,
    },
    input: {
      fontFamily: "Inter_700Bold",
      fontSize: 14,
      lineHeight: 17,
    },
    select: {
      fontFamily: "Inter_600SemiBold",
      fontSize: 14,
      lineHeight: 16,
    },
    buttonGroup: {
      fontFamily: "Inter_600SemiBold",
      fontSize: 18,
      lineHeight: 22,
    },
    titleList: {
      fontFamily: "Inter_700Bold",
      fontSize: 12,
      lineHeight: 14,
    },
    titleInformative: {
      fontFamily: "Inter_700Bold",
      fontSize: 20,
      lineHeight: 24,
    },
    titleBold: {
      fontFamily: "Inter_700Bold",
      fontSize: 12,
    },
  },
});



export type Theme = typeof theme;
export default theme;